'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../J.A.R.V.I.S. Dashboard - Copy/js/agent.js'),'utf8');
function setup(saved){const store={mission:saved};const listeners={};const events=[];const J={load:(k,f)=>store[k]??f,save:(k,v)=>store[k]=JSON.parse(JSON.stringify(v)),on:(n,f)=>(listeners[n]??=[]).push(f),emit:(n,v)=>{events.push(n);(listeners[n]||[]).forEach(f=>f(v));}};vm.runInNewContext(source,{window:{J},console,Date,Math,Set,Map,JSON,Object,String,Array,Number,Error});return {a:J.agent,J,store,events};}
const plan={title:'Repair fixture',steps:[{id:'inspect',title:'Inspect project',verification:'Relevant files read',kind:'observation'},{id:'fix',title:'Implement fix',verification:'Change applied and subsequent tests pass',kind:'change'},{id:'test',title:'Run tests',verification:'Exit code zero',kind:'validation'}]};
function running(p=plan){const x=setup();x.a.start(x.a.normalizePlan(p,'Inspect project, fix it and test it'));x.a.run();return x;}
function result(a,id,name,input,out){const c={id,name,input};assert.equal(a.beforeTool(c),true);return a.recordToolResult(c,out);}
test('conservative mission detection bypasses simple actions and chat',()=>{const {a}=setup();for(const s of ['what time is it','open spotify','pause music',"what’s the weather",'remember that my printer is upstairs','tell me about black holes','Explain how DNS works.'])assert.equal(a.needsMission(s),false,s);for(const s of ['inspect this repo, fix the issue, test it and tell me what changed','build me a portfolio site and test it','research these libraries and compare results','organize these files'])assert.equal(a.needsMission(s),true,s);});
test('plan parsing validates and normalizes without accepting policy fields',()=>{const {a}=setup();assert.equal(a.normalizePlan(JSON.stringify(plan),'trusted objective').objective,'trusted objective');assert.equal(a.normalizePlan('```json\n'+JSON.stringify(plan)+'\n```').steps.length,3);for(const p of ['{broken',{}, {...plan,steps:[]},{...plan,tools:[]},{...plan,steps:Array(11).fill(plan.steps[0])},{...plan,steps:Array(10).fill(plan.steps[0])}])assert.throws(()=>a.normalizePlan(p));const duplicate={...plan,steps:plan.steps.map(s=>({...s,id:'same'}))};assert.equal(new Set(a.normalizePlan(duplicate).steps.map(s=>s.id)).size,3);assert.throws(()=>a.normalizePlan({...plan,steps:[{...plan.steps[0],status:'completed'},plan.steps[1]]}));});
test('evidence-backed progression rejects fabricated IDs and write-only repairs',()=>{const {a,events}=running();let e=result(a,'read','files',{action:'read',project:'fixture',path:'main.py'},'Actual file contents');assert.equal(a.verifyStep('inspect','Read actual source',['fake']),false);assert.equal(a.verifyStep('inspect','Read source',[e.id]),true);const write=result(a,'write','files',{action:'write',project:'fixture',path:'main.py'},'Written main.py');assert.equal(a.verifyStep('fix','Fixed',[write.id]),false);a.observeFiles({action:'run',project:'fixture'},{ok:true,exit:1,summary:'test exited 1'});e=result(a,'bad','files',{action:'run',project:'fixture',what:'test'},'test exited 1 — it did NOT succeed');assert.equal(e.success,false);assert.equal(a.verifyStep('fix','Fixed',[write.id,e.id]),false);a.observeFiles({action:'run',project:'fixture'},{ok:true,exit:0,summary:'test exit code 0'});e=result(a,'good','files',{action:'run',project:'fixture',what:'test',entry:'tests.py'},'test finished cleanly, exit code 0');assert.equal(a.verifyStep('fix','Tests passed after change',[write.id,e.id]),true);assert.equal(a.verifyStep('test','Exit zero',[e.id]),true);assert.equal(a.current().status,'completed');assert.ok(events.includes('mission:complete'));assert.ok(events.includes('mission:step'));});
test('real check metadata overrides a superficially successful summary',()=>{const {a}=running();a.observeFiles({action:'check',project:'fixture'},{ok:true,problems:2,pages:1,summary:'Two problems found'});const e=result(a,'check','files',{action:'check',project:'fixture'},'Two problems found');assert.equal(e.success,false);});
test('failed calls retry only adjusted arguments, with at most two retries',()=>{const {a}=running();result(a,'a','files',{action:'read',path:'a'},'FAILED - absent');assert.equal(a.current().steps[0].status,'failed');result(a,'b','files',{action:'read',path:'b'},'FAILED - absent');result(a,'c','files',{action:'read',path:'c'},'FAILED - absent');assert.equal(a.beforeTool({id:'d',name:'files',input:{action:'read',path:'d'}}),false);assert.equal(a.current().status,'blocked');const x=running();result(x.a,'a','files',{action:'read',path:'a'},'FAILED - absent');assert.equal(x.a.beforeTool({id:'repeat',name:'files',input:{path:'a',action:'read'}}),false);assert.equal(x.a.current().status,'blocked');});
test('cancellation blocks all subsequent dispatch and late verification',()=>{const {a}=running();a.cancel();assert.equal(a.current().status,'cancelled');assert.equal(a.beforeTool({id:'a',name:'files',input:{action:'write'}}),false);assert.equal(a.verifyStep('inspect','Fake',['fake']),false);assert.equal(a.run(),false);assert.equal(a.intent('stop speaking'),'silence');assert.equal(a.intent('cancel that'),'cancel');});
test('approval waiting is not failure and rejection cannot become completion',()=>{const {a,J}=running();J.emit('diff-review',{id:'p'});assert.equal(a.current().status,'waiting_approval');J.emit('review-result',{id:'p',ok:true});assert.equal(a.current().status,'executing');J.emit('diff-review',{id:'p2'});J.emit('review-result',{id:'p2',ok:false});assert.equal(a.current().status,'blocked');});
test('replan preserves verified work and failed-call anti-thrash history',()=>{const {a}=running();const e=result(a,'r','files',{action:'read'},'read evidence');a.verifyStep('inspect','Read source',[e.id]);result(a,'bad','files',{action:'write',path:'bad'},'FAILED - refused');a.replan({title:'Revised',steps:[{id:'inspect',title:'Locate backend issue',verification:'Backend read'},{id:'test',title:'Run tests',verification:'Tests pass'}]},'Backend cause');assert.equal(a.current().steps[0].status,'completed');assert.equal(a.current().revisions.length,1);assert.equal(a.beforeTool({id:'again',name:'files',input:{action:'write',path:'bad'}}),false);});
test('reload restores active work as waiting, with no automatic execution',()=>{const {a,store}=running();const loaded=setup(store.mission);assert.equal(loaded.a.current().status,'waiting');assert.equal(loaded.a.executing(),false);assert.equal(loaded.a.current().steps[0].status,'pending');assert.equal(loaded.a.beforeTool({id:'x',name:'files',input:{action:'write'}}),false);loaded.a.run();assert.equal(loaded.a.executing(),true);});
test('parallel observations stay bounded; dependent mutations and checks are serial',()=>{const {a}=running();const cs=['read','read','write','run','read','read','read','read'].map((action,i)=>({id:String(i),name:'files',input:{action}}));assert.equal(JSON.stringify(a.batches(cs,3).map(b=>b.map(c=>c.input.action))),JSON.stringify([['read','read'],['write'],['run'],['read','read','read'],['read']]));});
test('structured planner is used only for missions and tool-less route is blocked',async()=>{const {a}=setup();let n=0;const model=async()=>{n++;return JSON.stringify(plan);};assert.equal(await a.prepare('open spotify',model,['files'],true),false);assert.equal(n,0);await a.prepare('inspect this project and fix it',model,['files'],false);assert.equal(n,1);assert.equal(a.current().status,'blocked');assert.equal(a.current().steps.every(s=>s.status!=='completed'),true);});
test('cancellation during planning cannot resurrect the mission',async()=>{const {a}=setup();await a.prepare('inspect project and fix it',async()=>{a.cancel();return JSON.stringify(plan);},['files'],true);assert.equal(a.current().status,'cancelled');});
test('correction pauses execution and preserves verified steps during revision',()=>{const {a}=running();const e=result(a,'r','files',{action:'read'},'read evidence');a.verifyStep('inspect','Read source',[e.id]);a.correct("No, don't modify that file.");assert.equal(a.current().status,'waiting');assert.equal(a.current().steps[0].status,'completed');assert.equal(a.beforeTool({id:'w',name:'files',input:{action:'write'}}),false);});
test('evidence is bounded and common credentials are redacted',()=>{const {a}=running();for(let i=0;i<80;i++)result(a,'r'+i,'files',{action:'read',path:String(i)},'api_key=EXAMPLE_PRIVATE_VALUE '+ 'x'.repeat(2000));assert.ok(a.current().evidence.length<=60);assert.ok(a.context().length<15000);assert.ok(!JSON.stringify(a.current()).includes('EXAMPLE_PRIVATE_VALUE'));});

test('older validation cannot verify a later write, even within the same timestamp',()=>{const {a}=running();const read=result(a,'r','files',{action:'read'},'source');a.verifyStep('inspect','Read',[read.id]);a.observeFiles({action:'run',project:'fixture'},{ok:true,exit:0,summary:'exit 0'});const old=result(a,'old','files',{action:'run',project:'fixture'},'exit code 0');const write=result(a,'w','files',{action:'write',project:'fixture',path:'main.py'},'Written');assert.equal(a.verifyStep('fix','Fixed',[write.id,old.id]),false);});
test('failure reproduction can use actual negative evidence without claiming passing validation',()=>{const {a}=running({title:'Diagnose failure',steps:[{id:'reproduce',title:'Reproduce failure',verification:'Actual failing program exit captured',kind:'validation'},{id:'test',title:'Run tests',verification:'Exit zero',kind:'validation'}]});a.observeFiles({action:'run',project:'fixture'},{ok:true,exit:1,summary:'SyntaxError'});const e=result(a,'bad','files',{action:'run',project:'fixture'},'exited 1 — it did NOT succeed');assert.equal(a.verifyStep('reproduce','Actual failure captured',[e.id]),true);assert.equal(a.verifyStep('test','Tests pass',[e.id]),false);});
test('explicit continuation cannot reset exhausted retries',()=>{const {a}=running();for(let i=0;i<3;i++)result(a,'r'+i,'files',{action:'read',path:String(i)},'FAILED - absent');a.finish();a.run();assert.equal(a.beforeTool({id:'r4',name:'files',input:{action:'read',path:'new'}}),false);assert.equal(a.current().status,'blocked');});
test('conversation clear drops the persisted mission',()=>{const {a,J,store}=running();J.emit('conversation-cleared');assert.equal(a.current(),null);assert.equal(store.mission,null);});

test('continuation cannot resubmit an identical rejected write',()=>{const {a,J}=running();const call={id:'w',name:'files',input:{action:'write',project:'fixture',path:'main.py',content:'print(99)'}};assert.equal(a.beforeTool(call),true);J.emit('diff-review',{id:'p'});J.emit('review-result',{id:'p',ok:false});a.run();assert.equal(a.beforeTool({...call,id:'again'}),false);assert.equal(a.current().status,'blocked');});

test('existing unknown-tool, exception and refusal returns are failed evidence',()=>{for(const output of ['Unknown tool: invented','Tool failed: controlled exception','Refused: invalid URL']){const {a}=running();const e=result(a,'r','invented',{},output);assert.equal(e.success,false);assert.equal(a.current().steps[0].status,'failed');}});

test('planning and ready use one mission identity and lifecycle start',async()=>{const {a,J,events}=setup();let planningId;await a.prepare('inspect project and fix it',async()=>{planningId=a.current().id;return JSON.stringify(plan);},['files'],true);assert.equal(a.current().id,planningId);assert.equal(events.filter(e=>e==='mission:start').length,1);});
