'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../J.A.R.V.I.S. Dashboard - Copy/js/agent.js'),'utf8');
function setup(saved){const store={mission:saved},events={};const J={load:(key,fallback)=>store[key]??fallback,save:(key,value)=>store[key]=JSON.parse(JSON.stringify(value)),on:(key,fn)=>(events[key]??=[]).push(fn),emit:(key,value)=>(events[key]||[]).forEach(fn=>fn(value))};vm.runInNewContext(source,{window:{J},Date,Math,Set,Map,JSON,Object,String,Array,Number,Error});return{J,a:J.agent,store};}
const plan={title:'Safe fixture',steps:[{id:'read',title:'Inspect',verification:'Read source',kind:'observation'},{id:'test',title:'Validate',verification:'Real check',kind:'validation'}]};
test('restoring concurrent approvals cannot clear another pending action or auto-run',()=>{
 const x=setup();x.a.start(x.a.normalizePlan(plan,'safe'));x.a.run();x.J.emit('permission:waiting',{id:'one',capability:'READ_FILE'});x.J.emit('permission:waiting',{id:'two',capability:'READ_FILE'});
 const y=setup(x.store.mission);assert.equal(y.a.current().status,'waiting_approval');assert.equal(y.a.run(),false);assert.equal(y.a.beforeTool({id:'r',name:'files',input:{action:'read'}}),false);
 y.J.emit('permission:recovered',{id:'one',action:{tool:'files',input:{action:'read',project:'fixture'}},output:'Actual first read'});assert.equal(y.a.current().pendingPermissions.length,1);assert.equal(y.a.current().status,'waiting_approval');y.a.finish();assert.equal(y.a.current().status,'waiting_approval');
 y.J.emit('permission:recovered',{id:'two',action:{tool:'files',input:{action:'read',project:'fixture'}},output:'Actual second read'});assert.equal(y.a.current().pendingPermissions.length,0);assert.equal(y.a.current().status,'executing');assert.equal(y.a.current().evidence.length,2);
});
test('late approval cannot resurrect cancelled mission',()=>{const {a,J}=setup();a.start(a.normalizePlan(plan,'safe'));a.run();J.emit('permission:waiting',{id:'one',capability:'WRITE_FILE'});a.cancel();J.emit('permission:resolved',{id:'one',ok:true});assert.equal(a.current().status,'cancelled');assert.equal(a.beforeTool({id:'w',name:'files',input:{action:'write'}}),false);});
test('policy denial records evidence and blocks before protected dispatch',()=>{const {a,J}=setup();a.start(a.normalizePlan(plan,'safe'));a.run();J.emit('permission:resolved',{id:'policy-denial',ok:false,reason:'read_only_task_boundary'});assert.equal(a.current().status,'blocked');assert.equal(a.current().evidence[0].success,false);assert.match(a.current().evidence[0].summary,/PERMISSION_DENIED/);assert.equal(a.beforeTool({id:'w',name:'files',input:{action:'write'}}),false);});
