/* Native Windows registry checks; disposable server/files, controlled model and Spotify bridge. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const root=path.join(__dirname,'..'),app=path.join(root,'J.A.R.V.I.S. Dashboard - Copy'),folder=fs.mkdtempSync(path.join(os.tmpdir(),'jarvis-phase4-native-')),port=18780,base='http://localhost:'+port;
fs.cpSync(path.join(app,'skills'),path.join(folder,'skills'),{recursive:true});fs.mkdirSync(path.join(folder,'skills','malformed'));fs.writeFileSync(path.join(folder,'skills','malformed','skill.json'),'{invalid');fs.mkdirSync(path.join(folder,'fixture'));fs.writeFileSync(path.join(folder,'fixture','main.py'),'print(42)\n');
const python=cp.execFileSync('py',['-3.12','-c','import sys; print(sys.executable)'],{encoding:'utf8'}).trim();let server,browser;const results=[],requests=[];
const record=text=>{results.push(text);console.log(text);};
async function wait(test){const end=Date.now()+20000;while(Date.now()<end){if(await test())return;await new Promise(r=>setTimeout(r,100));}assert.fail('Timed out');}
async function start(){server=cp.spawn(python,['tests/skills-native-server.py',String(port),folder],{cwd:root,windowsHide:true,stdio:['ignore','ignore','pipe']});let errors='';server.stderr.on('data',data=>{errors+=data;});await wait(async()=>{if(server.exitCode!==null)throw Error('Fixture server exited: '+errors);try{return(await fetch(base+'/api/health')).ok;}catch(e){return false;}});}
async function stop(){if(server&&server.exitCode===null){server.kill();await new Promise(resolve=>server.once('exit',resolve));}}
(async()=>{await start();browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:1080},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.addInitScript(base=>{if(window!==window.top)return;localStorage.setItem('jarvis.v7.settings',JSON.stringify({provider:'openai',altBase:base+'/mock/v1',altModel:'fixture-model',apiKey:'EXAMPLE_FOR_OFFLINE_TEST_ONLY',visionModel:'fixture-vision',webSearch:true,routeLocal:false,speak:false,wakeWord:false,autoListen:false,critique:'off',reviewWrites:'off',buildCheck:'off',fastModel:''}));},base);
await page.route('**/*',route=>{const u=new URL(route.request().url());return ['localhost','127.0.0.1'].includes(u.hostname)?route.continue():route.abort();});
await page.route('**/mock/v1/chat/completions',async route=>{const body=route.request().postDataJSON();requests.push(body);return route.fulfill({contentType:'text/event-stream',body:'data: '+JSON.stringify({choices:[{index:0,delta:{content:'Normal fixture chat.'}}]})+'\n\ndata: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n'});});
let spotify=0;await page.route('**/api/spotify/command',async route=>{assert.equal(route.request().postDataJSON().action,'current');spotify++;return route.fulfill({json:{ok:true,summary:'Fixture track',track:'Fixture',playing:true}});});
await page.goto(base);await page.waitForFunction(()=>window.J?.skills&&J.brain&&!document.body.classList.contains('booting'));await page.evaluate(()=>J.skills.load());
let snap=await page.evaluate(()=>J.skills.diagnostics());assert.equal(snap.health.loaded,17);assert.equal(snap.invalid.length,1);record('Boot discovers 17 valid skills; malformed fixture is isolated: PASS');
await page.evaluate(()=>J.brain.send('Explain how DNS works.'));assert.equal(requests.at(-1).tools.length,21);assert.equal(await page.evaluate(()=>J.agent.current()),null);record('Normal chat and 21 equivalent OpenAI tools work with registry: PASS');
await page.evaluate(()=>J.brain.send('What does this code do?'));assert.equal(requests.at(-1).model,'jarvis-coder:6.7b');assert.equal(requests.at(-1).tools,undefined);record('Existing tool-less local specialist serializes no tools and normal chat succeeds: PASS');
await page.route('**/api/skills',route=>route.fulfill({status:503,json:{ok:false,error:'Controlled outage'}}));
await page.evaluate(async()=>{try{await J.skills.load(true);}catch(e){}});await page.evaluate(()=>J.brain.send('Explain DNS during this outage.'));assert.equal(requests.at(-1).tools.length,3);assert.match(await page.evaluate(()=>J.skills.execute('files',{action:'read',project:'fixture',path:'main.py'},{})),/^FAILED/);await page.unroute('**/api/skills');await page.evaluate(()=>J.skills.load(true));record('Registry outage keeps normal chat/core tools and fails closed for integrations: PASS');
const noSession=await context.request.post(base+'/api/skills/command',{data:{action:'set_enabled',id:'files',enabled:false}});assert.equal(noSession.status(),400);for(const file of ['jarvis_skills_state.json','jarvis_skills_state.json.tmp'])assert.equal((await context.request.get(base+'/'+file)).status(),403);assert.equal(await page.evaluate(()=>J.skills.enabled('files')),true);record('Skill management requires trusted UI session; runtime state and transient file are private: PASS');
await page.evaluate(()=>J.skills.setEnabled('memory',false));assert.equal((await context.request.post(base+'/api/memory/command',{data:{action:'set',text:'Must not be created',when:'in 2 hours'}})).status(),403);assert.equal((await context.request.get(base+'/api/memory/due')).status(),200);await page.evaluate(()=>J.skills.setEnabled('memory',true));record('Reminder disable blocks direct commands while required memory and due delivery remain functional: PASS');
const list=await page.evaluate(()=>J.skills.list());assert.ok(list.find(s=>s.id==='spotify'));assert.equal(list.find(s=>s.id==='vision').status,'available');record('Current skill availability and diagnostics are visible: PASS');
assert.match(await page.evaluate(()=>J.skills.execute('spotify',{action:'current'},{userText:'What is playing?'})),/Fixture track/);assert.equal(spotify,1);record('Spotify registry route invokes existing bridge (controlled playback fixture): PASS');
assert.match(await page.evaluate(()=>J.skills.execute('files',{action:'read',project:'fixture',path:'main.py'},{})),/print\(42\)/);record('Files registry adapter performs real allowed read: PASS');
let work=page.evaluate(()=>J.skills.execute('files',{action:'write',project:'fixture',path:'approved.txt',content:'approved fixture'},{}));
await page.locator('#permissionsSurface .permission-card').filter({hasText:'approved.txt'}).getByRole('button',{name:'Allow once',exact:true}).click();assert.ok(!/^FAILED/.test(await work));assert.equal(fs.readFileSync(path.join(folder,'fixture','approved.txt'),'utf8'),'approved fixture');record('Protected write ASK suspends; allow once executes real exact write: PASS');
work=page.evaluate(()=>J.skills.execute('files',{action:'write',project:'fixture',path:'denied.txt',content:'must not write'},{}));await page.locator('#permissionsSurface .permission-card').filter({hasText:'denied.txt'}).getByRole('button',{name:'Deny once',exact:true}).click();assert.match(await work,/FAILED/);assert.equal(fs.existsSync(path.join(folder,'fixture','denied.txt')),false);record('Permission DENY leaves real fixture unchanged: PASS');
const scheduled=await page.evaluate(()=>J.skills.execute('tasks',{action:'create',title:'Registry safe check',objective:'Inspect the fixture project and run tests.',schedule:'in 2 hours'},{userText:'Jarvis, in 2 hours inspect this project and run tests.'}));assert.ok(!/^FAILED/.test(scheduled),scheduled);record('Task adapter saves trusted future objective through existing durable engine: PASS');
await page.evaluate(()=>J.skills.setEnabled('files',false));await page.evaluate(()=>J.brain.send('Explain DNS again.'));assert.equal(requests.at(-1).tools.some(t=>t.function.name==='files'),false);assert.equal(requests.at(-1).tools.some(t=>t.function.name==='see_preview'),false);assert.match(await page.evaluate(()=>J.skills.execute('files',{action:'read',project:'fixture',path:'main.py'},{})),/^FAILED/);
const raw=await context.request.post(base+'/api/files/command',{data:{action:'read',project:'fixture',path:'main.py'}});assert.equal(raw.status(),403);record('Disable removes Files/dependent Preview from model and blocks direct dispatch: PASS');
await page.reload();await page.waitForFunction(()=>window.J?.skills&&!document.body.classList.contains('booting'));assert.equal(await page.evaluate(()=>J.skills.enabled('files')),false);await stop();await start();await page.reload();await page.waitForFunction(()=>window.J?.skills&&!document.body.classList.contains('booting'));assert.equal(await page.evaluate(()=>J.skills.enabled('files')),false);record('Enabled state survives browser reload and actual server restart: PASS');
await page.evaluate(()=>J.skills.setEnabled('files',true));await page.evaluate(()=>J.skills.refresh());assert.equal(await page.evaluate(()=>J.skills.enabled('files')),true);assert.match(await page.evaluate(()=>J.skills.execute('files',{action:'read',project:'fixture',path:'main.py'},{})),/print\(42\)/);record('Re-enable and explicit refresh restore existing file routing: PASS');
await page.evaluate(()=>{J.permissions.show();document.getElementById('permissionsSurface').hidden=true;J.skills.show();});
for(const width of [390,768,1280,1920]){await page.setViewportSize({width,height:1080});await page.waitForTimeout(500);const before=await page.evaluate(()=>({scrollY,orb:document.getElementById('orb').getBoundingClientRect().toJSON()}));await page.evaluate(()=>J.skills.show());await page.waitForTimeout(300);const after=await page.evaluate(()=>({scrollY,width:innerWidth,scroll:document.documentElement.scrollWidth,orb:document.getElementById('orb').getBoundingClientRect().toJSON(),composer:document.getElementById('input').getBoundingClientRect().toJSON(),panel:document.querySelector('.skills-surface').getBoundingClientRect().toJSON()}));const overlap=(a,b)=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;assert.equal(after.scroll,width);assert.equal(after.orb.width,before.orb.width);assert.ok(Math.abs(after.orb.top+after.scrollY-before.orb.top-before.scrollY)<1);assert.equal(overlap(after.panel,after.orb),false);assert.equal(overlap(after.panel,after.composer),false);}
record('Skills UI at 390/768/1280/1920 preserves geometry with no overflow or overlaps: PASS');assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,tests:results.length,results,fixture:folder},null,2));await context.close();
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await stop();});
