/* Windows integration: real SQLite/file tools, controlled provider SSE, no paid calls. */
'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const base = process.env.JARVIS_TEST_URL || 'http://localhost:18763';
const artifacts = process.env.JARVIS_TEST_ARTIFACTS;
const results = [], geometry = [];
const originalPush = results.push.bind(results); results.push = value => { console.log(value); return originalPush(value); };
const plan = {title:'Safe project check',steps:[{id:'inspect',title:'Read project source',verification:'Actual source read',kind:'observation'},{id:'test',title:'Run validation',verification:'Actual program exits zero',kind:'validation'}]};
(async () => {
 const browser = await chromium.launch({headless:true});
 const request = await browser.newContext();
 async function api(action, data={}) {const response=await request.request.post(base+'/api/tasks/command',{data:{action,...data}});const value=await response.json();assert.equal(value.ok,true,JSON.stringify(value));return value;}
 try {
  const initial = await api('list'); for (const run of initial.runs) if(['queued','claimed','running','waiting_approval','interrupted'].includes(run.status)) await api('cancel_run',{run_id:run.id});
  const fixtureRoot=fs.mkdtempSync(path.join(os.tmpdir(),'jarvis-phase2-project-'));fs.mkdirSync(path.join(fixtureRoot,'fixture'));const file=path.join(fixtureRoot,'fixture','main.py');fs.writeFileSync(file,'print(42)\n');
  assert.equal((await (await request.request.post(base+'/api/files/command',{data:{configure:true,roots:[fixtureRoot],projects:fixtureRoot}})).json()).ok,true);
  async function session() {
   const context=await browser.newContext({viewport:{width:1280,height:1080},reducedMotion:'reduce'}), page=await context.newPage(), errors=[];
   let mode='read', execution=0, plans=0;const dispatch=[];
   page.on('pageerror',e=>errors.push(e.message));
   await page.addInitScript(base=>{if(window!==window.top)return; if(!localStorage.getItem('jarvis.v7.settings')) localStorage.setItem('jarvis.v7.settings',JSON.stringify({provider:'openai',altBase:base+'/mock/v1',altModel:'fixture-model',apiKey:'EXAMPLE_FOR_OFFLINE_TEST_ONLY',speak:true,wakeWord:false,autoListen:false,critique:'off',reviewWrites:'off',buildCheck:'on',fastModel:'',showThinking:false}));},base);
   await page.route('**/*',async route=>{
    const url=new URL(route.request().url());
    if(url.pathname==='/api/knowledge')return route.fulfill({json:{ok:false,error:'Offline fixture'}});
    if(url.pathname==='/api/health')return route.fulfill({json:{tasks:true,files:true}});
    if(url.pathname==='/api/files/command'){dispatch.push(route.request().postDataJSON().action);return route.continue();}
    if(url.pathname.endsWith('/chat/completions')) {
     const body=route.request().postDataJSON(), system=body.messages[0].content;let text='',calls=[];
     if(system.includes('Create 2-8')){plans++;assert.equal(body.tools,undefined);text=mode==='planner-error'?'Malformed planner JSON':JSON.stringify(mode==='write'?{title:'Reviewed write',steps:[{id:'change',title:'Write safe correction',verification:'Reviewed change validated by actual program run',kind:'change'},{id:'test',title:'Run validation',verification:'Program exits zero',kind:'validation'}]}:plan);}
     else if(system.includes('Evaluate the stated verification')) {
      assert.equal(body.tools,undefined);const mission=await page.evaluate(()=>J.agent.current()), done=[];
      const current=mission.steps[mission.currentStep],read=mission.evidence.find(e=>e.tool==='files:read'&&e.success),good=mission.evidence.slice().reverse().find(e=>e.tool==='files:run'&&e.success),write=mission.evidence.find(e=>e.kind==='change'&&e.success);
      if(current?.id==='inspect'&&read)done.push({id:'inspect',summary:'Actual source read',evidence:[read.id]});
      if(current?.id==='test'&&good)done.push({id:'test',summary:'Actual program exit 0 and output 42',evidence:[good.id]});
      if(current?.id==='change'&&write&&good)done.push({id:'change',summary:'Reviewed write validated by exit 0',evidence:[write.id,good.id]},{id:'test',summary:'Program exit 0',evidence:[good.id]});
      text=JSON.stringify({completed:done,decision:'continue',reason:'Actual evidence only',plan:null});
     } else {
      execution++;
      if(mode==='planner-error')text='No valid JSON.';
      else if(mode==='chat')text='Ordinary chat still works.';
      else if(mode==='schedule'&&execution===1)calls=[{id:'schedule',name:'tasks',input:{action:'create',title:'Model-created brief',objective:'Read calendar and weather and summarize.',schedule:'every morning at 8'}}];
      else if(mode==='schedule')text='The durable task was saved.';
      else if(mode==='failure')calls=[{id:'missing'+execution,name:'files',input:{action:'read',project:'fixture',path:'missing.txt'}}];
      else if(mode==='write'&&execution===1)calls=[{id:'write',name:'files',input:{action:'write',project:'fixture',path:'main.py',content:'print(6 * 7)\n'}}];
      else if(mode==='write'&&execution===2)calls=[{id:'run',name:'files',input:{action:'run',project:'fixture',what:'python',entry:'main.py'}}];
      else if(mode==='resume'&&execution===1)calls=[{id:'run',name:'files',input:{action:'run',project:'fixture',what:'python',entry:'main.py'}}];
      else if(mode==='read'&&execution<=2)calls=[{id:'call'+execution,name:'files',input:execution===1?{action:'read',project:'fixture',path:'main.py'}:{action:'run',project:'fixture',what:'python',entry:'main.py'}}];
      else text='Observed results are ready.';
     }
     const delta=calls.length?{content:'Checking the safe project. ',tool_calls:calls.map((call,index)=>({index,id:call.id,type:'function',function:{name:call.name,arguments:JSON.stringify(call.input)}}))}:{content:text};
     return route.fulfill({contentType:'text/event-stream',body:['data: '+JSON.stringify({model:'fixture-model',choices:[{index:0,delta}]}),'data: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:calls.length?'tool_calls':'stop'}]}),'data: [DONE]'].join('\n\n')+'\n\n'});
    }
    if(['localhost','127.0.0.1'].includes(url.hostname))return route.continue();return route.abort();
   });
   await page.goto(base);await page.waitForFunction(()=>window.J?.tasks&&J.app&&!document.body.classList.contains('booting'));
   await page.evaluate(()=>{window.__voiceCalls=[];for(const method of ['feed','flush','say'])J.voice[method]=()=>window.__voiceCalls.push(method);window.speechSynthesis.speak=()=>window.__voiceCalls.push('synthesis');});
   return {page,context,errors,dispatch,setMode(value){mode=value;execution=0;},counts:()=>({plans,execution})};
  }
  async function create(title, policy='read_only', seconds=1) {return (await api('create',{title,objective:'Inspect the safe fixture project and run validation.',schedule:{type:'once',at:Date.now()/1000+seconds},run_policy:policy,request_key:title+'-'+Date.now()})).task;}
  async function completed(task, state='completed') {
   await assertEventually(async()=>{const runs=(await api('history',{task:task.id})).runs;return runs[0]?.status===state;});
   return (await api('history',{task:task.id})).runs[0];
  }
  async function assertEventually(check) {const until=Date.now()+35000;while(Date.now()<until){if(await check())return;await new Promise(resolve=>setTimeout(resolve,250));}assert.fail('Timed out waiting for durable run state.');}
  let x=await session();x.setMode('chat');await x.page.evaluate(()=>J.brain.send('Explain how DNS works.'));assert.equal(x.counts().plans,0);assert.ok((await x.page.evaluate(()=>window.__voiceCalls)).length>0);await x.page.evaluate(()=>{window.__voiceCalls=[];});results.push('Ordinary chat bypasses planning and retains normal speech hooks: PASS');
  x.setMode('schedule');await x.page.evaluate(()=>J.brain.send('Every morning at 8 check my calendar and weather and prepare a brief.'));assert.equal(x.counts().plans,0);const saved=(await api('list')).tasks.find(task=>task.title==='Model-created brief');assert.ok(saved);await api('cancel',{task:saved.id});results.push('Model-visible tasks tool saves recurring user objective without immediate mission execution: PASS');
  x.setMode('read');await x.page.evaluate(()=>{window.__voiceCalls=[];});const safe=await create('Near-future safe check');await new Promise(resolve=>setTimeout(resolve,1200));await x.page.evaluate(()=>J.tasks.poll());const run=await completed(safe);assert.ok(run.mission_id);assert.equal(x.counts().plans,1);assert.ok(x.dispatch.includes('run'));assert.deepEqual(await x.page.evaluate(()=>window.__voiceCalls),[]);
  const snapshot=(await api('get_run',{run_id:run.id})).run.mission_snapshot;assert.equal(snapshot.status,'completed');assert.ok(snapshot.steps.every(step=>step.status==='completed'&&step.evidence.length));
  const notices=await (await request.request.post(base+'/api/memory/command',{data:{action:'notices'}})).json();assert.equal(notices.notices.filter(n=>n.source.endsWith(run.id)).length,1);results.push('Real scheduled queue → claim → Phase 1 planning/read/run/verifier → durable receipt → one silent notice: PASS');
  await x.page.reload();await x.page.waitForFunction(()=>window.J?.tasks&&J.app&&!document.body.classList.contains('booting'));assert.equal((await api('history',{task:safe.id})).runs[0].status,'completed');results.push('Native browser reload retains task/history and does not rerun completed work: PASS');await x.context.close();
  const queued=await create('No-browser queue');await new Promise(resolve=>setTimeout(resolve,1200));assert.equal((await api('due')).runs.find(r=>r.task_id===queued.id).status,'queued');results.push('With no dashboard worker, server queues work without headless model execution: PASS');
  x=await session();const y=await session();await Promise.all([x.page.evaluate(()=>J.tasks.poll()),y.page.evaluate(()=>J.tasks.poll())]);const queuedRun=await completed(queued);assert.equal(queuedRun.attempt,1);assert.equal(x.counts().plans+y.counts().plans,1);results.push('Two real browser workers claim and execute one occurrence once: PASS');await x.context.close();await y.context.close();
  x=await session();x.setMode('write');const rejected=await create('Protected scheduled write','reviewed_writes');await new Promise(resolve=>setTimeout(resolve,1200));let running=x.page.evaluate(()=>J.tasks.poll());await x.page.waitForFunction(()=>J.agent.current()?.status==='waiting_approval');await assertEventually(async()=>{const r=(await api('history',{task:rejected.id})).runs[0];return r?.status==='waiting_approval';});assert.equal(fs.readFileSync(file,'utf8'),'print(42)\n');await x.page.getByRole('button',{name:'Reject',exact:true}).first().click();await running;await completed(rejected,'failed');assert.equal(fs.readFileSync(file,'utf8'),'print(42)\n');assert.ok(!x.dispatch.includes('apply'));assert.deepEqual(await x.page.evaluate(()=>window.__voiceCalls),[]);results.push('Scheduled write overrides review=off, waits in existing diff UI, rejects without writing or speaking: PASS');await x.context.close();
  x=await session();x.setMode('write');const approved=await create('Approved scheduled correction','reviewed_writes');await new Promise(resolve=>setTimeout(resolve,1200));running=x.page.evaluate(()=>J.tasks.poll());await x.page.waitForFunction(()=>J.agent.current()?.status==='waiting_approval');await x.page.getByRole('button',{name:'Apply',exact:true}).first().click();await running;await completed(approved);assert.equal(fs.readFileSync(file,'utf8'),'print(6 * 7)\n');assert.deepEqual(await x.page.evaluate(()=>window.__voiceCalls),[]);results.push('Approved scheduled write reuses real file application and existing build validation: PASS');await x.context.close();
  x=await session();x.setMode('write');const denied=await create('Default read-only boundary');await new Promise(resolve=>setTimeout(resolve,1200));await x.page.evaluate(()=>J.tasks.poll());await completed(denied,'failed');assert.equal(x.dispatch.filter(action=>['write','propose','apply'].includes(action)).length,0);results.push('Default background policy refuses writes before any file action: PASS');await x.context.close();
  x=await session();x.setMode('failure');const failed=await create('Controlled tool failure');await new Promise(resolve=>setTimeout(resolve,1200));await x.page.evaluate(()=>J.tasks.poll());await completed(failed,'failed');assert.equal(x.dispatch.filter(action=>action==='read').length,1);results.push('Phase 1 anti-thrash blocks repeated failing calls; scheduler does not retry forever: PASS');await x.context.close();
  x=await session();x.setMode('planner-error');const plannerFailed=await create('Controlled planner failure');await new Promise(resolve=>setTimeout(resolve,1200));await x.page.evaluate(()=>J.tasks.poll());await completed(plannerFailed,'failed');assert.equal(x.counts().plans,1);assert.equal(x.dispatch.length,0);results.push('Malformed planner output becomes one failed run without tool execution or infinite planner retries: PASS');await x.context.close();
  // Reload after a verified read while the dependent run is not yet dispatched.
  x=await session();const interrupted=await create('Interrupted safe mission');await x.page.route('**/api/tasks/command',async route=>{const data=route.request().postDataJSON();if(data.action==='check_claim'&&await x.page.evaluate(()=>J.agent.current()?.steps?.[0]?.status==='completed'))await new Promise(resolve=>setTimeout(resolve,4000));return route.continue();});await new Promise(resolve=>setTimeout(resolve,1200));running=x.page.evaluate(()=>J.tasks.poll()).catch(()=>{});await x.page.waitForFunction(()=>J.agent.current()?.steps?.[0]?.status==='completed');await new Promise(resolve=>setTimeout(resolve,700));await x.page.reload();await running;await x.page.waitForFunction(()=>window.J?.tasks&&J.app&&!document.body.classList.contains('booting'));console.log('Reload worker diagnostic:',await x.page.evaluate(()=>({worker:J.tasks.diagnostics(),pointer:!!sessionStorage.getItem('jarvis-durable-claim'),mission:J.agent.current()?.status})));await completed(interrupted,'interrupted');const beforeResume=(await api('history',{task:interrupted.id})).runs[0];const beforeSnapshot=(await api('get_run',{run_id:beforeResume.id})).run.mission_snapshot;assert.equal(beforeSnapshot.steps[0].status,'completed');const stamp=beforeSnapshot.steps[0].completedAt;
  await x.page.unroute('**/api/tasks/command');x.setMode('resume');await api('resume_run',{run_id:beforeResume.id});await x.page.evaluate(()=>J.tasks.poll());const resumed=await completed(interrupted);assert.equal(resumed.mission_id,beforeResume.mission_id);assert.equal((await api('get_run',{run_id:resumed.id})).run.mission_snapshot.steps[0].completedAt,stamp);results.push('Reload interrupts; explicit resume retains mission identity and verified step without replay: PASS');await x.context.close();
  // Cancellation while existing review is outstanding must discard the proposal.
  fs.writeFileSync(file,'print(42)\n');x=await session();x.setMode('write');const cancelled=await create('Cancel scheduled mission','reviewed_writes');await new Promise(resolve=>setTimeout(resolve,1200));running=x.page.evaluate(()=>J.tasks.poll());await x.page.waitForFunction(()=>J.agent.current()?.status==='waiting_approval');const cancelRun=(await api('history',{task:cancelled.id})).runs[0];await x.page.evaluate(run_id=>J.tasks.manage('cancel_run',{run_id}),cancelRun.id);await running;assert.equal((await api('get_run',{run_id:cancelRun.id})).run.status,'cancelled');assert.ok(!x.dispatch.includes('apply'));results.push('Cancel run calls existing mission abort and prevents reviewed application: PASS');await x.context.close();
  x=await session();
  for(const width of [390,768,1280,1920]) {
   await x.page.setViewportSize({width,height:1080});await x.page.waitForTimeout(1000);const before=await x.page.evaluate(()=>({scrollY:window.scrollY,orb:document.querySelector('#orb').getBoundingClientRect().toJSON(),input:document.querySelector('#input').getBoundingClientRect().toJSON()}));
   await x.page.evaluate(()=>J.tasks.show());await x.page.waitForFunction(()=>document.querySelector('#taskList .durable-task'));await x.page.waitForTimeout(1000);const shape=await x.page.evaluate(()=>({scrollY:window.scrollY,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,dialog:document.querySelector('.tasks-surface').getBoundingClientRect().toJSON(),orb:document.querySelector('#orb').getBoundingClientRect().toJSON(),input:document.querySelector('#input').getBoundingClientRect().toJSON()}));assert.equal(shape.scrollWidth,width);assert.equal(shape.orb.width,before.orb.width);assert.equal(shape.orb.height,before.orb.height);assert.ok(Math.abs(shape.orb.left-before.orb.left)<1);assert.ok(Math.abs((shape.orb.top+shape.scrollY)-(before.orb.top+before.scrollY))<1,'Reactor document geometry changed');assert.equal(shape.input.width,before.input.width);assert.equal(shape.input.height,before.input.height);assert.ok(shape.dialog.left>=0&&shape.dialog.right<=width);const overlaps=(a,b)=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;assert.equal(overlaps(shape.dialog,shape.orb),false);assert.equal(overlaps(shape.dialog,shape.input),false);geometry.push(shape);if(artifacts)await x.page.screenshot({path:path.join(artifacts,'phase2-'+width+'.png')});await x.page.locator('#tasksClose').click();
  }
  assert.deepEqual(x.errors,[]);results.push('Task transcript surface at 390/768/1280/1920 has no overflow or reactor/composer overlap: PASS');
  await x.page.evaluate(()=>J.tasks.show());await x.page.waitForFunction(()=>document.querySelector('#taskList .durable-task'));
  await x.page.locator('#taskCreate').locator('..').locator('summary').click();
  const uiTitle='UI safe brief '+Date.now();await x.page.locator('#taskTitle').fill(uiTitle);await x.page.locator('#taskObjective').fill('Read the safe fixture project and report its state.');await x.page.locator('#taskSchedule').fill('in 2 hours');await x.page.locator('#taskCreate button[type=submit]').click();
  await assertEventually(async()=>!!(await api('list')).tasks.find(t=>t.title===uiTitle));
  const uiTask=(await api('get',{task:uiTitle})).task;assert.equal(uiTask.run_policy,'read_only');await x.page.waitForFunction(title=>Array.from(document.querySelectorAll('.durable-task')).some(e=>e.textContent.includes(title)),uiTitle);
  let uiRow=x.page.locator('.durable-task').filter({hasText:uiTitle});await uiRow.getByRole('button',{name:'Pause',exact:true}).click();assert.equal((await api('get',{task:uiTask.id})).task.status,'paused');await uiRow.getByRole('button',{name:'Resume schedule',exact:true}).click();assert.equal((await api('get',{task:uiTask.id})).task.status,'active');await uiRow.getByRole('button',{name:'Cancel schedule',exact:true}).click();assert.equal((await api('get',{task:uiTask.id})).task.status,'cancelled');results.push('Native task form creates durable work; existing-style controls pause, resume and cancel future scheduling: PASS');assert.deepEqual(x.errors,[]);await x.context.close();
  const response=await request.request.post(base+'/api/tasks/command',{headers:{Origin:'https://untrusted.invalid'},data:{action:'list'}});assert.equal(response.status(),403);for(const name of ['jarvis_tasks.db','jarvis_tasks.db-wal','jarvis_tasks.db-shm'])assert.equal((await request.request.get(base+'/'+name)).status(),403);results.push('Cross-origin task mutations rejected; all task database filenames remain private: PASS');
  const report={results,geometry,liveModels:false,realAccountActions:false};if(artifacts)fs.writeFileSync(path.join(artifacts,'phase2-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 } finally {await request.close();await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
